server:
  port: 8080

spring:
  application:
    name: CherryAccountsApi
  datasource:
    url: jdbc:mysql://localhost:3306/accounts
    password: 1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true